### ISSUE TITLE
Add builder pattern to ComponentWidget

### ISSUE THREAD

**Issue by drewdeponte** [uptech/flutter_forge#18]
The idea with this is to use the `builder` pattern with `ComponentWidget` instead of using inheritence.

This was raised as an idea by @chillbrodev within the context of how you override the UI of a component while keeping all the logic, etc.

Currently this is supported by creating a new Widget that inherits from the specific ComponentWidget and then overwritting the `build` method.

If my understanding is correct from the discussion I believe the idea is to optionally be able to provide a `builder` function to the constructor of the component and if provided use that `builder` for the content of body. Otherwise use the body that is provided as part of the component.

I am not sure exactly what this would look like yet. It is something we will have to explore.

@chillbrodev please add in comments or clearifications to what I have posted here.

**Comment by chillbrodev** [comment]
Yes the understanding is correct, I'll take a stab at providing a sample of how it could look.

**Comment by drewdeponte** [comment]
This has been integrated and released as part of v0.8.0. Therefore, I am closing this issue.
